/**
 * Servicios de dominio — única lógica invocada por tRPC (UI), REST, MCP y
 * Colyseus (ADR-010/022). Todos los servicios reciben un `actor` explícito y
 * sus dependencias se inyectan, de modo que se testean sin infraestructura.
 */
export * from "./actor";
export * from "./catalog";
export * from "./catalog-listing";
export * from "./reviews";
export * from "./reviews-prisma-store";
export * from "./room-package-repository";
export * from "./room-draft";
export * from "./room-draft-prisma-store";
export * from "./admin";
export * from "./platform-settings";
export * from "./pricing-tiers";
export * from "./admin-prisma-store";
export * from "./audio-assets";
export * from "./audio-assets-prisma-store";
export * from "./credits";
export * from "./credits-prisma-store";
export * from "./elevenlabs-client";
export * from "./audio-generation";
export * from "./room-publish";
export * from "./room-publish-prisma-store";
export * from "./publish-confirmation";
export * from "./events";
export * from "./events-prisma-store";
export * from "./access-keys";
export * from "./access-keys-prisma-store";
export * from "./join-token";
export * from "./redeem";
export * from "./room-license";
export * from "./room-license-prisma-store";
export * from "./invitations";
export * from "./invitations-prisma-store";
export * from "./access-key-cards";
export * from "./access-key-cards-pdf";
export * from "./access-key-cards-prisma-store";
export * from "./organizations";
export * from "./organizations-prisma-store";
export * from "./event-progress";
export * from "./event-runtime";
export * from "./event-runtime-prisma-store";
export * from "./event-panel";
export * from "./moderation";
export * from "./moderation-precheck";
export * from "./moderation-prisma-store";
export * from "./user-data-rights";
export * from "./user-data-rights-prisma-store";
export * from "./purchases";
export * from "./purchases-prisma-store";
export * from "./creator-connect";
export * from "./creator-connect-prisma-store";
export * from "./stripe-gateway";
export * from "./stripe-webhook-dedupe";
export * from "./contact";
export * from "./legal-acceptance";
export * from "./legal-acceptance-prisma-store";
